<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Gustav\Thesis\Block\Frontend\Stores $block */

$categories = $block->getJsonCategories();
?>

<div id="store-list" class="store-list-container" data-bind="scope: 'stores'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "#store-list": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "stores": {
                        "component": "storeList",
                        "actionUrl": "<?= $escaper->escapeUrl($block->getUrl('storelocator/frontend/storelist')) ?>",
                        "categoriesData": "<?= $escaper->escapeJs($categories) ?>"
                    }
                }
            }
        }
    }
</script>
